---
version: "3.4"
services:
  data-transport-layer:
    image: ethereumoptimism/data-transport-layer:${DTL_IMAGE_TAG:-latest}
    restart: ${RESTART}
    env_file:
      - ${SHARED_ENV_PATH}/data-transport-layer.env
      - .env
    volumes:
      - dtl:/db
  l2geth-replica:
    image: ethereumoptimism/l2geth:${L2GETH_IMAGE_TAG:-latest}
    restart: ${RESTART}
    stop_grace_period: 3m
    entrypoint:
      - /bin/sh
      - -c
      #- "sleep infinity"
      - "/scripts/check-for-chaindata.sh && /scripts/l2geth-replica-start.sh"
    env_file:
      - ${SHARED_ENV_PATH}/l2geth-replica.env
      - .env
    volumes:
      - geth:/geth
      - ./kustomize/replica/bases/configmaps/:/scripts/
  replica-healthcheck:
    image: ethereumoptimism/replica-healthcheck:${HC_IMAGE_TAG:-latest}
    restart: ${RESTART}
    env_file:
      - kustomize/replica/envs/kovan/replica-healthcheck.env
      - .env
    volumes:
      - ./kustomize/replica/bases/configmaps/:/scripts/
volumes:
  dtl:
  geth:
