---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: l2geth-replica
spec:
  template:
    spec:
      containers:
        - name: l2geth-replica
          command:
            - geth
            - --datadir=/geth
            - --pprof
            - --pprofaddr
            - "0.0.0.0"
            - --pprofport
            - "6060"
          resources:
            limits:
              memory: 30Gi
            requests:
              memory: 20Gi
