apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mainnet-replica-0-3-0

resources:
  - ../bases/data-transport-layer
  - ../bases/l2geth-replica
  - ../bases/configmaps
  - ../bases/servicemonitors
  - ./l2geth-volume.yaml

configMapGenerator:
  - name: data-transport-layer
    envs:
      - replica-data-transport-layer.env
  - name: l2geth-replica
    envs:
      - replica-l2geth.env

images:
  - name: ethereumoptimism/data-transport-layer
    newName: ethereumoptimism/data-transport-layer
    newTag: 0.4.3
  - name: ethereumoptimism/l2geth
    newName: ethereumoptimism/l2geth
    newTag: 0.4.3

patchesStrategicMerge:
  - patch-l2geth-resources.yaml

# patches:
#   - path: patch-l2geth-volumes.yaml
#     target:
#       group: apps
#       version: v1
#       kind: StatefulSet
#       name: l2geth-replica