---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: l2geth-replica
spec:
  template:
    spec:
      containers:
        - name: l2geth-replica
          resources:
            limits:
              cpu: "2"
              memory: 16Gi
            requests:
              cpu: "1"
              memory: 12Gi
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: data-transport-layer
spec:
  template:
    spec:
      containers:
        - name: data-transport-layer
          resources:
            limits:
              cpu: 500m
              memory: 2Gi
            requests:
              cpu: 256m
              memory: 500Mi
