---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: l2geth-replica
spec:
  template:
    spec:
      containers:
        - name: l2geth-replica
          resources:
            limits:
              memory: 30Gi
            requests:
              memory: 20Gi
