---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: l2geth-replica-data
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: premium-rwo
  resources:
    requests:
      storage: 100Gi
