apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kovan-replica-0-4-13
commonLabels:
  network: kovan
  provider: internal

bases:
  - ../../envs/kovan

resources:
  - ../../bases/data-transport-layer
  - ../../bases/l2geth-replica
  - ../../bases/configmaps
  - ../../bases/servicemonitors
  - ../../bases/replica-healthcheck
  - ./l2geth-volume.yaml

images:
  - name: ethereumoptimism/data-transport-layer
    newName: ethereumoptimism/data-transport-layer
    newTag: 0.4.6
  - name: ethereumoptimism/l2geth
    newName: ethereumoptimism/l2geth
    newTag: 0.4.13
  - name: ethereumoptimism/replica-healthcheck
    newName: ethereumoptimism/replica-healthcheck
    newTag: 0.2.1

patchesStrategicMerge:
  - ./patches/l2geth-resources.yaml

patches:
  - path: ./patches/l2geth-volume.yaml
    target:
      group: apps
      version: v1
      kind: StatefulSet
      name: l2geth-replica