---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: l2geth-replica
spec:
  template:
    spec:
      containers:
        - name: l2geth-replica
          command:
            - geth
            - --datadir=/geth
            - --pprof
            - --pprofaddr
            - "0.0.0.0"
            - --pprofport
            - "6060"
          env:
            - name: IPC_DISABLE
              value: "false"
          resources:
            limits:
              cpu: "2"
              memory: 8Gi
            requests:
              cpu: "1"
              memory: 4Gi
